owasp-dep-scan/dep-scan

- .flake8
- .github/workflows/pythonapp.yml
- depscan/cli.py
- depscan/lib/analysis.py
- depscan/lib/audit.py
- depscan/lib/bom.py
- depscan/lib/config.py
- depscan/lib/license.py
- depscan/lib/logger.py
- depscan/lib/normalize.py
- depscan/lib/pkg_query.py
- depscan/lib/privado.py
- depscan/lib/utils.py
- test/test_analysis.py
- test/test_bom.py
> Lint comments

- depscan/cli.py
- depscan/lib/utils.py
Fixes #121 
I have added the function for getting the version. Could you point in the code where do I need to edit the metadata?
> feat: add version flag

- depscan/cli.py
> Pretty print vex

- .github/workflows/dockertests.yml
- .github/workflows/gobintests.yml
- .github/workflows/pythonapp.yml
- README.md
- contrib/CSAF_README.md
- contrib/csaf.toml
- depscan/cli.py
- depscan/lib/csaf.py
- pyproject.toml
- test/data/product_tree.json
- test/test_csaf.py
Syncing the `fix/project-type` branch to have the latest changes.
* Adds 3.12 tests
* Adds 3.12 tests
---------
> Adds 3.12 tests (#137)

- README.md
Fix for https://github.com/owasp-dep-scan/dep-scan/issues/112
> Fixing oras link in README

- depscan/cli.py
- depscan/lib/analysis.py
- depscan/lib/bom.py
- depscan/lib/csaf.py
> Enable reachability analysis

- depscan/cli.py
- depscan/lib/bom.py
- depscan/lib/explainer.py
Bug fixes around nydus unpack which was failing with directories containing space.
> simplify explain

- README.md
- depscan/cli.py
- depscan/lib/analysis.py
- depscan/lib/utils.py
- pyproject.toml
- test/data/report-template.j2
- test/test_utils.py
Resolves #140 
Please give it a close look, this is my first piece of python for over a decade ;)
> #140 - Option to create custom reports using Jinja

- depscan/cli.py
- depscan/lib/normalize.py
- pyproject.toml
> Use vendor alias only for name based searches

- Dockerfile
- depscan/cli.py
- depscan/lib/bom.py
- docker-compose.yml
- pyproject.toml
Fixes #233 
- Clone the repo and switch to this branch
- Change the volumes in docker compose
- docker compose up
```
curl http://0.0.0.0:7070/cache
curl --json '{"url": "https://github.com/HooliCorp/vulnerable-aws-koa-app", "type": "js"}' http://0.0.0.0:7070/scan
```
> Do not crash when used with url

- .github/workflows/dockertests.yml
- .github/workflows/gobintests.yml
- .github/workflows/pythonapp.yml
- depscan/cli.py
- depscan/lib/bom.py
- docker-compose.yml
- pyproject.toml
Same fix for #233 ported to v6 branch
> Fixes #233 in v6

- .github/workflows/dockertests.yml
- .github/workflows/pythonpublish.yml
- depscan/cli.py
- Add checking of an environment variable for use with the [AppThreat/dep-scan-action](https://github.com/appthreat/dep-scan-action). User will have to run action with the value "I have sponsored OWASP-dep-scan.".
- Updated workflow actions.
> Adds checking env variable for github actions for 5.x

- depscan/lib/analysis.py
Same as https://github.com/owasp-dep-scan/dep-scan/pull/244 for v5
> Improves sub-tree display

- .github/workflows/dockertests.yml
- .github/workflows/gobintests.yml
- contrib/free_disk_space.sh
- depscan/lib/csaf.py
> Trim ci agents

- .github/workflows/dockertests.yml
- .github/workflows/gobintests.yml
- depscan/lib/csaf.py
> Trim CI. Fixes a CSAF error

- depscan/lib/config.py
- depscan/lib/normalize.py
- depscan/lib/utils.py
> Support for gem with platform name in the version number

- pyproject.toml
> Handle zero scores from npm with vdb 5.6.3

- depscan/lib/audit.py
> Added more alias for js audit

- depscan/lib/orasclient.py
- pyproject.toml
backports: https://github.com/owasp-dep-scan/dep-scan/pull/271
> backport: Add compatibility for future oras releases

- flake.lock
- flake.nix
closes: #270
This should add a devshell for `nix develop`, and a buildable/runnable package using `nix build` or `nix run`
> Add nix flake using pyproject.nix 

- flake.lock
- flake.nix
backports: https://github.com/owasp-dep-scan/dep-scan/pull/277
> backport: Add pyproject.nix flake

- depscan/lib/analysis.py
- depscan/lib/config.py
- depscan/lib/normalize.py
- pyproject.toml
> Adhoc FP and FN fixes

- depscan/lib/analysis.py
- depscan/lib/config.py
- depscan/lib/normalize.py
- pyproject.toml
> Port various false positives fixes from v5

- Dockerfile
- depscan/lib/utils.py
- pyproject.toml
Update cdxgen to 10.3.0 to bring go purl compat fixes
> Update cdxgen to bring go purl compatibility fixes

- depscan/lib/normalize.py
> Aliases for dotnet runtime

- .github/workflows/pythonapp.yml
- .gitignore
- Dockerfile
- README.md
- contrib/npm-watch.py
- depscan/cli.py
- depscan/lib/analysis.py
- depscan/lib/bom.py
- depscan/lib/config.py
- depscan/lib/pkg_query.py
- pyproject.toml
- test/data/npm-biome-cli-metadata.json
- test/data/npm-biome-metadata.json
- test/data/npm-fsevents-metadata.json
- test/data/npm-sqlite3-metadata.json
- test/test_license.py
- test/test_pkg_query.py
- vendor/spdx/json/licenses.json
Based on #311 but supports more.
> Risk audit improvements

- depscan/lib/analysis.py
- depscan/lib/normalize.py
> Fix for generic packages false positives for v6

- depscan/lib/audit.py
- depscan/lib/package_query/cargo_pkg.py
Looks for binary names in metadata provided from crates.io.
> Feat: add package can include binaries

- depscan/lib/normalize.py
> Removed project alias for pypi which was resulting in FP

- depscan/lib/normalize.py
- pyproject.toml
> Do not suffix s for all pypi packages. Fixes #341

- .github/workflows/csafdemo.yml
- .github/workflows/gobintests.yml
- depscan/lib/config.py
- pyproject.toml
```
python depscan/cli.py --purl "pkg:composer/phenx/php-svg-lib@0.4.1" --reports-dir /tmp/reports
Dependency Scan Results (COMPOSER)
╔═════════════════════════════════════════════════════════════════════════╤══════════════════╤═══════════════════════╤══════════════════╤════════════╗
║ CVE                                                                     │ Insights         │ Fix Version           │ Severity         │      Score ║
╟─────────────────────────────────────────────────────────────────────────┼──────────────────┼───────────────────────┼──────────────────┼────────────╢
║ php-svg-lib@0.4.1 ⬅ CVE-2023-50251                                      │                  │ 0.5.2                 │ HIGH             │        7.5 ║
╟───────────────────────────────────────────────────────────── …
```
> Adds alias for dompdf

- .github/workflows/csafdemo.yml
- .github/workflows/gobintests.yml
- depscan/lib/analysis.py
- depscan/lib/bom.py
- depscan/lib/config.py
- depscan/lib/utils.py
- pyproject.toml
- test/test_csaf.py
Search by cpe and url is not tested yet though. The alias is similar to #358
> Adds alias for dompdf. Support for search by cpe and url

- depscan/cli.py
- depscan/lib/analysis.py
- depscan/lib/bom.py
- depscan/lib/csaf.py
- depscan/lib/explainer.py
- depscan/lib/utils.py
Use CJD functions for io operations.
> Use cjd libs for io.

- depscan/cli.py
Fixes issue https://github.com/owasp-dep-scan/dep-scan/issues/368
> Fix: quart fix

- depscan/cli.py
- test/snapshots.py
> Fix issue #371 cli args.

- depscan/lib/analysis.py
- depscan/lib/csaf.py
- pyproject.toml
- test/test_csaf.py
Handles prioritizing cvss v4 for vdr and filters it out for csaf.
> Update metrics for cvss v4

- documentation/.readthedocs.yaml
- documentation/docusaurus.config.ts
Adds `.readthedocs.yaml` configuration to the project
> Docs: add .readthedocs.yaml

- README.md
- documentation/docs/dep-scan.mdx
Update README to add funding section
> Docs: add NLNET funding

- .config/depscan-dev.toml
- .github/workflows/csafdemo.yml
- .github/workflows/dockertests.yml
- .github/workflows/gobintests.yml
- .github/workflows/pythonapp.yml
- .github/workflows/pythonpublish.yml
- .gitignore
- Dockerfile
- README.md
- depscan/cli.py
- depscan/lib/analysis.py
- depscan/lib/bom.py
- depscan/lib/logger.py
- depscan/lib/tomlparse.py
- documentation/docs/Develop/getting-started-development.mdx
- documentation/docs/cli-usage.mdx
- documentation/docs/migrate-v5-to-v6.mdx
- pyproject.toml
- uv.lock
- vendor/spdx/json/licenses.json
Use blint for binary-analysis and lifecycle=post-build
> Support for config file

- .github/workflows/csafdemo.yml
- .github/workflows/dockertests.yml
- .github/workflows/gobintests.yml
- .github/workflows/justbuild.yml
- .github/workflows/pre-commit.yml
- .github/workflows/pythonapp.yml
- .github/workflows/snapshot_tests.yml
- Dockerfile
- README.md
- depscan/cli.py
- depscan/lib/bom.py
- depscan/lib/config.py
- depscan/lib/logger.py
- documentation/docs/Develop/getting-started-development.mdx
- documentation/docs/cli-usage.mdx
- documentation/docs/env-var.mdx
- documentation/docs/migrate-v5-to-v6.mdx
- packages/xbom-lib/pyproject.toml
- packages/xbom-lib/src/xbom_lib/__init__.py
- packages/xbom-lib/src/xbom_lib/blint.py
- packages/xbom-lib/src/xbom_lib/cdxgen.py
- pyproject.toml
- uv.lock
BOM engine to use is now configurable.
> Refactored bom generation with the new xbom-lib package

- .github/workflows/dockertests.yml
- depscan/cli.py
- depscan/lib/bom.py
- documentation/docs/migrate-v5-to-v6.mdx
- packages/analysis-lib/src/analysis_lib/output.py
- packages/analysis-lib/src/analysis_lib/utils.py
- packages/analysis-lib/src/analysis_lib/vdr.py
Improved prioritization logic
Improved false positives handling
Container escape vulns prediction
> container bom analysis

- .github/workflows/repotests.yml
- README.md
- depscan/cli.py
- depscan/cli_options.py
- depscan/lib/bom.py
- depscan/lib/config.py
- depscan/lib/explainer.py
- depscan/lib/tomlparse.py
- depscan/lib/utils.py
- documentation/docs/cli-usage.mdx
- documentation/docs/migrate-v5-to-v6.mdx
- documentation/docs/reachability-analysis.mdx
- packages/analysis-lib/src/analysis_lib/__init__.py
- packages/analysis-lib/src/analysis_lib/csaf.py
- packages/analysis-lib/src/analysis_lib/output.py
- packages/analysis-lib/src/analysis_lib/reachability.py
- packages/analysis-lib/src/analysis_lib/utils.py
- packages/analysis-lib/src/analysis_lib/vdr.py
- packages/xbom-lib/src/xbom_lib/blint.py
- packages/xbom-lib/src/xbom_lib/cdxgen.py
- pyproject.toml
- uv.lock
Numerous bug fixes to improve the results for JS projects. Some example reports generated with this PR:
[juice-shop](https://github.com/user-attachments/files/19840289/depscan.txt)
[vulnerable-aws-koa-app](https://github.com/user-attachments/files/19840293/depscan.txt)
> Semantic analysis improvements

- .github/workflows/repotests-lifecycle-c.yml
- .github/workflows/repotests-lifecycle-dotnet.yml
- .github/workflows/repotests-lifecycle-go.yml
- .github/workflows/repotests-lifecycle-java.yml
- .github/workflows/repotests.yml
- contrib/depscanGPT/README.md
- contrib/free_disk_space.sh
- depscan/lib/bom.py
- documentation/docs/env-var.mdx
- packages/analysis-lib/src/analysis_lib/__init__.py
- packages/analysis-lib/src/analysis_lib/output.py
- packages/analysis-lib/src/analysis_lib/reachability.py
- pyproject.toml
- uv.lock
Primitive binary reachability by tracking reachable frameworks and cryptos that are bundled. Tested with a dotnet project.
[depscan.txt](https://github.com/user-attachments/files/19852609/depscan.txt)
> semantics dotnet

- .github/workflows/repotests-lifecycle-dotnet.yml
- .github/workflows/repotests-lifecycle-go.yml
- .github/workflows/repotests-lifecycle-java.yml
- .github/workflows/repotests.yml
- depscan/lib/explainer.py
- pyproject.toml
- uv.lock
Improved Explanations for python flows. Added repotests.
> Python semantic analysis tweaks

- .github/workflows/repotests.yml
- depscan/lib/explainer.py
- packages/analysis-lib/src/analysis_lib/output.py
- packages/analysis-lib/src/analysis_lib/utils.py
- packages/xbom-lib/src/xbom_lib/cdxgen.py
> c semantics

- .github/workflows/dockertests.yml
- .github/workflows/gobintests.yml
- .github/workflows/justbuild.yml
- .github/workflows/pythonapp.yml
- .github/workflows/pythonpublish.yml
- .github/workflows/repotests-lifecycle-c.yml
- .github/workflows/repotests-lifecycle-dotnet.yml
- .github/workflows/repotests-lifecycle-go.yml
- .github/workflows/repotests-lifecycle-java.yml
- .github/workflows/repotests.yml
- .github/workflows/snapshot_tests.yml
- Dockerfile
- depscan/lib/bom.py
- depscan/lib/explainer.py
- devenv.lock
- devenv.nix
- packages/analysis-lib/pyproject.toml
- packages/xbom-lib/pyproject.toml
- packages/xbom-lib/src/xbom_lib/cdxgen.py
- pyproject.toml
- uv.lock
Update packages.
Increase cdxgen timeout to 30 minutes.
> cdxgen sane defaults

- packages/reporting-lib/src/reporting_lib/htmlgen.py
[samples20250718.zip](https://github.com/user-attachments/files/21312467/samples20250718.zip)
> minor bugfixes
