depscan/cli.py

Added CLI flag `--no-license-scan` that allows you to disable license limitation scanning.

Adding flag for disabling license scan

---

setup.py

Allow third-party tools (e. g., PyPI or `pyp2rpm`) to get the license details in a simple way.

Add license entry

---

.github/workflows/pythonpublish.yml
depscan/lib/normalize.py
pyproject.toml

Also, use name_project alias in vendor only for composer. With better sources such as osv these aliasing can be tuned down further over time.
This will tune the FPs while dealing with application CVEs.
Fixes #113
@ashmedai @bh86 could you kindly test with this branch?

Filter vendor aliases that are also name aliases.

---

.github/workflows/dockertests.yml
README.md
depscan/cli.py
depscan/lib/config.py
pyproject.toml

The current scheme uses the [vdb library](https://pypi.org/project/appthreat-vulnerability-db/) to sequentially download the vulnerability data from NVD, OSV, GitHub, etc. advisories. However, there exists a [vdb image](https://github.com/AppThreat/vdb/pkgs/container/vdb) that has the data from all these advisories baked into it. Hence, instead of sequentially downloading data, the image artifacts can be downloaded.
Note:
* This commit removes the "--cache-os" argument as it is no longer needed. The OS vulnerability data exists in the vdb image.
* This commit does NOT remove the "--sync" argument as one might want to just sync (get the latest vulnerability data) instead of downloading everything.

Using oras-py to download the vulnerability data.

---

.github/workflows/dockertests.yml

- Expands matrix to run everything on all OSes, 
- Adds running pytest tests for all os x python-version
- Addresses codec issue in ms_test on Windows, 
- Combines ms_test and version_tests2 for efficiency (leaves version_tests separate due to multiple python versions in matrix).
- Adds improved artifacts names so that artifacts aren't written over due to using same artifact name for all runs in matrix
Successful [run](https://github.com/cerrussell/dep-scan/actions/runs/6366805280).
We may want to clarify what is being tested by renaming this workflow and certain steps in the future since Docker and containers don't appear to be involved.
Closes #135

Expand, improve, consolidate dockertests

---

.github/workflows/dockertests.yml
.github/workflows/gobintests.yml
.github/workflows/pythonapp.yml
pyproject.toml

https://github.com/owasp-dep-scan/dep-scan/blob/master/depscan/lib/utils.py#L376

Adds 3.12 tests

---

README.md
contrib/CSAF_README.md
contrib/csaf.toml
depscan/cli.py
depscan/lib/csaf.py
pyproject.toml
test/data/product_tree.json
test/test_csaf.py

New feature - CSAF generation
- Adds the option to output a csaf document with vulnerability results.

CSAF Generation

---

.editorconfig
.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/false_positive.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
depscan/cli.py
pyproject.toml

Sometimes there are
```
Traceback (most recent call last):
File "/usr/local/bin/depscan", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.9/site-packages/depscan/cli.py", line 1118, in main
vdr_file=vdr_file,
UnboundLocalError: local variable 'vdr_file' referenced before assignment
```
errors on depscan executions, thus declaring all variables used for the
reporting that are initialized only conditionally upfront.

Declare variables required for report

---

README.md

Adds links for headings in our ReadMe for easier navigation per #199 .

chore: Add a table of contents at the beginning of README.md

---

depscan/cli.py
depscan/lib/analysis.py
depscan/lib/csaf.py
pyproject.toml
test/test_analysis.py
test/test_csaf.py

- Added full CVSS scoring to properties of pkg_vulnerabilities objects with function `cvss_to_vdr()`
- If the CVSS vector string indicates the version is 3.0 rather than the default 3.1, updates this in `pkg_vulnerabilities` objects
- Added date metadata where available to the published and updated fields of `pkg_vulnerabilities` objects for use in csaf
- Parse CWEs so that multiple CWEs can be listed in the vdr (csaf will continue to add extra CWEs to notes) with `split_cwe()` function
- Reverted to using `bom_file` rather than `vdr_file` for `import_root_component` as a csaf does not need to have a vulnerability section to be valid, but no vulnerabilities means there will be no vdr_file.
- Added source providing the vulnerability data to csaf vulnerability acknowledgement
- Replaced the …

Reuse pkg_vulnerabilities list instead of results list for CSAF generation

---

depscan/cli.py
pyproject.toml

Executing `depscan --report-template depscan.j2 --bom empty.json` with
`empty.json` being only `{}`, depscan fails with
```
Traceback (most recent call last):
File "/home/heubeck/.local/bin/depscan", line 8, in <module>
sys.exit(main())
^^^^^^
File "/home/heubeck/.local/lib/python3.12/site-packages/depscan/cli.py", line 1041, in main                                                                                          pkg_vulnerabilities=pkg_vulnerabilities,
^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'pkg_vulnerabilities' where it is not associated with a value
```
Added the with 5.1.6 newly introduced vars to the initialization similar
to the other variables provided to the jinja engine.

Fix undeclared vars for custom report creation.

---

depscan/lib/analysis.py
pyproject.toml

The presence of a POC alone doesn't make a vulnerability exploitable. This is clarified with an insight, `Reachable Bounty target.`

Clarify bounty targets in insights

---

.github/workflows/pythonpublish.yml
Dockerfile
pyproject.toml

Related: https://github.com/oras-project/oras-py/pull/123/files#r1469483979

Update cdxgen to bring dotnet universal tree fix

---

pyproject.toml

5.6.1 does a better job of resolving cve alias for osv.

Use vdb 5.6.1

---

.github/workflows/dockertests.yml
.github/workflows/pythonpublish.yml
depscan/cli.py

- Add checking of an environment variable for use with the [AppThreat/dep-scan-action](https://github.com/appthreat/dep-scan-action). User will have to run action with the value "I have sponsored OWASP-dep-scan.".
- Updated workflow actions.

Adds checking env variable for github actions for 6.x

---

depscan/lib/normalize.py
pyproject.toml

For the attached sbom, we get results for all versions of axios from both npm and osv. Previously, osv results were getting lost due to the use of `npm` as the vendor name.
```
Dependency Scan Results (JS)
╔═══════════════════════════════════════════════════════════════════╤═══════════════════════════════════╤═══════════════════╤══════════════╤═════════╗
║ Dependency Tree                                                   │ Insights                          │ Fix Version       │ Severity     │   Score ║
╟───────────────────────────────────────────────────────────────────┼───────────────────────────────────┼───────────────────┼──────────────┼─────────╢
║ snowflake-sdk@1.9.0                                               │ 📓 Indirect dependency            │ 1.6.0             │ MEDIUM       │ …
```

Expand the scope of npm alias to search for vendor with the name npm

---

depscan/cli.py
depscan/lib/normalize.py

Trying to get the src_dir from the bom path is good, but we need to still set src_dir to the current working directory if depscan hasn't been run using the --bom argument (or when the bom does not actually exist). Otherwise, we will run into problems as we later assume src_dir has been set and try to use it, which will result in an exception.
```python
if not src_dir or src_dir == ".":
if src_dir == "." or args.search_purl:
src_dir = os.getcwd()
elif args.bom and os.path.exists(args.bom):
src_dir = os.path.dirname(os.path.realpath(args.bom))
``` 
This PR corrects the problem.

Corrects scenario where no src_dir is set -5.x

---

depscan/lib/config.py
depscan/lib/normalize.py
pyproject.toml

Example:
```
"group": "",
"name": "bcrypt_pbkdf",
"version": "1.1.0-x64-mingw32",
```
The version number would be aliased to `1.1.0`. Requires cdxgen 10.1.2.

Support for gem with platform name in the version number

---

depscan/cli.py
depscan/lib/normalize.py
pyproject.toml

Trying to get the src_dir from the bom path is good, but we need to still set src_dir to the current working directory if depscan hasn't been run using the --bom argument (or when the bom does not actually exist). Otherwise, we will run into problems as we later assume src_dir has been set and try to use it, which will result in an exception.
```python
if not src_dir or src_dir == ".":
if src_dir == "." or args.search_purl:
src_dir = os.getcwd()
elif args.bom and os.path.exists(args.bom):
src_dir = os.path.dirname(os.path.realpath(args.bom))
``` 
This PR corrects the problem, as well as a couple other minor improvements to improve quality and maintainability.

Corrects scenario where no src_dir is set - 6.x

---

Dockerfile

stream=21 would result in node 16 getting installed, so surprised depscan image is even working.

Use nodejs 20 LTS

---

depscan/lib/config.py
depscan/lib/normalize.py
pyproject.toml

Fixes #262 
```
python depscan/cli.py --purl "pkg:pypi/azure-storage-blob@12.8.0" --reports-dir /tmp/reports
```
```
Dependency Scan Results (PYPI)
╔════════════════════════════════════════════════════════════════════════════╤═════════════════╤═══════════════════════╤═════════════════╤═══════════╗
║ CVE                                                                        │ Insights        │ Fix Version           │ Severity        │     Score ║
╟────────────────────────────────────────────────────────────────────────────┼─────────────────┼───────────────────────┼─────────────────┼───────────╢
║ azure-storage-blob@12.8.0 ⬅ CVE-2022-30187                                 │                 │ 12.13.0               │ MEDIUM          │       4.7 ║ …
```

Added alias for azure. Thanks NVD

---

depscan/lib/config.py
depscan/lib/normalize.py

PR# 263 for v6

---

depscan/lib/analysis.py
depscan/lib/normalize.py

when scan on sboms from trivy and syft sometimes happens keyerror. This PR fixes it.

fixing keyerror in version and purl

---

depscan/lib/orasclient.py
pyproject.toml

`get_manifest` seem to have an extra parameter in oras-py. Adding this should not break v0.1.26, but should allow flexibility for package manager repositories that only contains future versions.

Add compatibility for future oras releases

---

depscan/lib/analysis.py
depscan/lib/pkg_query.py
pyproject.toml

Consider deprecated packages as more risky. Ported to v6

---

depscan/cli.py
depscan/lib/bom.py

Creating a new PR for this one with signed commits.
It can be populated in two ways:
With the `--cdxgen-args` argument:
or
With the `CDXGEN_ARGS` environment variable:

Added generic cdxgen_args that can be passed as an environment variable or argument to depscan itself.

---

Dockerfile
depscan/lib/config.py
depscan/lib/normalize.py
pyproject.toml

numpy:numpy must be reported for pypi:numpy. However, redis:redis must not be reported for pypi:redis even though it has CPE similar to numpy.
This is fixed by adding numpy to package_alias and filtering vendor == name for non-nuget ecosystems.

depscan was reporting redis:redis for pypi:redis

---

Dockerfile

Fixes: #304 
docker image size: 2.82 GB (3032606438 bytes)

[Fix] Dockerfile - almalinux build is broken and make python version an argument

---

depscan/lib/config.py
depscan/lib/pkg_query.py

Fixes #317 
```
Risk Audit Summary (npm)
╔════════════════════════════════════════════╤════════════════╤══════════════════════════╤═══════════════════════════════════════════════════════════╗
║ Package                                    │ Used?          │               Risk Score │ Identified Risks                                          ║
╟────────────────────────────────────────────┼────────────────┼──────────────────────────┼───────────────────────────────────────────────────────────╢
║ phantomjs-prebuilt                         │ N/A            │                     0.44 │ ❌ Deprecated                                             ║
║                                            │                │                          │ ❌ Includes binary                                        ║
║ …
```

Use the bin block and name suffixes to report possible binary

---

README.md
contrib/npm-binaries/README.md
contrib/npm-binaries/collect.py
contrib/npm-binaries/requirements.txt
depscan/lib/config.py
depscan/lib/pkg_query.py
pyproject.toml

Added a contrib script to search for npm packages using keywords and look for binary risk (based on metadata) in them.
Added hishel package so that risk audit could optionally use valkey cache to reduce http lookups.

npm binary research

---

depscan/lib/analysis.py
depscan/lib/normalize.py

Restricting generic package searches to only those with version numbers, since the precision of purl from cdxgen is quite low.
Restricting Malware hits to only those with purls.
Fixes #320

Fix for generic packages false positives

---

Dockerfile

This solves an issue found in docker images reported in cdxgen issues where the wrong version of python was being used inside of docker images. [cdxgen #1195](https://github.com/CycloneDX/cdxgen/discussions/1195)

FIX: ensure python3.12 in docker image

---

Dockerfile
depscan/lib/normalize.py
pyproject.toml

CVEs are no longer reported for `pkg:pypi/pulp@2.9.0` with this fix.

Removed project alias for pypi which was resulting in FP

---

depscan/lib/analysis.py

This solves an issue where a purl does exists but the reachable label is skipped as vendor param is missing.
Ref: https://github.com/owasp-dep-scan/dep-scan/discussions/339#discussioncomment-10594626

fix: add reachable label when a purl does not have a vendor

---

depscan/lib/normalize.py
pyproject.toml
test/test_norm.py

The below no longer results in false positives.
```
python depscan/cli.py --purl "pkg:maven/org.tukaani/xz@1.9?type=jar" --reports-dir /tmp/reports
```

Removes aliasing for namespaces that affected maven

---

contrib/report-templates/sarif-all.j2
contrib/report-templates/sarif-crit.j2

Hi guys! Please consider to add two templates for SARIF reports (first for all found vulns, sercond for most critical with exploints, used or reachable modules with high risk vulns).
Format is the same as in Govulncheck.

Add two jinja templates for SARIF (all and only critical)

---

.github/workflows/snapshot_tests.yml

In order to test what we intend to test, we need to cache the vulnerability database used for the snapshot testing to be implemented in #355.

Cache vdb for consistence in snapshot tests.

---

depscan/lib/analysis.py
pyproject.toml
test/test_analysis.py

Brings cvss v4 support for v5 branch. Also fixes an npm severity inconsistency bug by updating to vdb 5.8.1.
```
python depscan/cli.py --purl "pkg:npm/dompurify@2.3.6" --reports-dir /tmp/reports
██████╗ ███████╗██████╗ ███████╗ ██████╗ █████╗ ███╗   ██╗
██╔══██╗██╔════╝██╔══██╗██╔════╝██╔════╝██╔══██╗████╗  ██║
██║  ██║█████╗  ██████╔╝███████╗██║     ███████║██╔██╗ ██║
██║  ██║██╔══╝  ██╔═══╝ ╚════██║██║     ██╔══██║██║╚██╗██║
██████╔╝███████╗██║     ███████║╚██████╗██║  ██║██║ ╚████║
╚═════╝ ╚══════╝╚═╝     ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═══╝
INFO [2024-11-10 23:19:47,496] No package risks detected ✅
Dependency Scan Results (NPM)
╔═══════════════════════════════════════════════════════════════════╤════════════════════╤═════════════════════════╤═══════════════════╤═════════════╗
║ CVE …
```

Support for cvss v4

---

depscan/lib/csaf.py
test/test_csaf.py

Ensures we only include cvss ratings that meet the CSAF 2.0 spec.

Filter out cvss v4 for CSAF, include multiple ratings.

---

documentation/docusaurus.config.ts

The location for docusarus edit has changed to `/documentation`. I tested this with a local docker docusarus setup; please review before merge.

issue-390: Fixed the editURL of docusaurus

---

README.md
depscan/cli.py
depscan/lib/analysis.py
pyproject.toml
uv.lock

Blint is available under groups "ext" and "all". This will keep the core package lightweight.

Integrate blint as an extension

---

contrib/bom-1.6.schema.json
contrib/depscanGPT/README.md
contrib/vex-validate.py
depscan/cli.py
depscan/lib/bom.py
depscan/lib/explainer.py
packages/analysis-lib/src/analysis_lib/__init__.py
packages/analysis-lib/src/analysis_lib/output.py
packages/analysis-lib/src/analysis_lib/utils.py
packages/analysis-lib/src/analysis_lib/vdr.py

Show patch locations in the priority table.

Track identity evidences in VDR

---

depscan/cli.py
depscan/lib/bom.py

In some sbom files "tools" does not contain "components" section, the fix solves the error in such files
Vdr file is created in the same folder of sbom, now it's created in the report folder if --reports-dir is set otherwise in the same folder of sbom file

Annotate_vdr: fix reading metadata.get("tools", {}).get("components", {}), create vdr file in report folder
